language: java
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/hibernate/rx
jobs:
  include:
    - stage: test
      name: "Run tests"
      jdk: openjdk8
      script: ./gradlew test -Pdocker
